### ISSUE TITLE
Release `Mango` with stable Node.js 16

### ISSUE THREAD

**Issue by Sitole** [goforboom/mango#2]
Actual Mongo Docker image supports Node.js 14 but active state ends by end of October 2021.
Its time to upgrade Docker image and use current version 16 (version 15 is skipped).

More about Node.js support plan: https://nodejs.org/en/about/releases/

**Comment by Sitole** [comment]
Right now official Alpine Linux repository contains only Node.js 14.17. We can wait 2-3 weeks and then check if there has been any change. If not, we can use some other repository with the current version.

Node.js package in Alpine Linux repository:
https://pkgs.alpinelinux.org/package/edge/main/x86/nodejs

**Comment by Sitole** [comment]
Finalized and released.

**Comment by landsman** [comment]
Cool. Just think that this kind of change is more for major version :)

**Comment by Sitole** [comment]
> Cool. Just think that this kind of change is more for major version :)

Sure, my fault 🤦🏻‍♂️
